ALTER TABLE "tenants"
ADD COLUMN IF NOT EXISTS "logo_url" TEXT,
ADD COLUMN IF NOT EXISTS "booking_enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "booking_start_time" TEXT NOT NULL DEFAULT '08:00',
ADD COLUMN IF NOT EXISTS "booking_end_time" TEXT NOT NULL DEFAULT '20:00',
ADD COLUMN IF NOT EXISTS "booking_working_days" INTEGER[] NOT NULL DEFAULT ARRAY[1,2,3,4,5,6]::INTEGER[];
